filename = open("data/local/dict/silence_phones.txt",'w')
filename.write('sil\n')
filename.close()
filename = open("data/local/dict/optional_silence.txt",'w')
filename.write('sil\n')
filename.close()
